---
# yamllint disable rule:line-length

name: Documentation
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main", "release-*"]
  pull_request:
    branches: ["main", "release-*"]
  # This workflow must be able to be triggered manually so that it can be
  # started from another workflow
  workflow_dispatch:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Install prereqs
        run: |
          echo 'APT::Acquire::Retries "5";' | sudo tee /etc/apt/apt.conf.d/80-retries
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip python3-venv

      - name: Build docs
        run: |
          cd docs
          ./setup-env.sh
          . ../.venv/bin/activate
          make html
